project:
  type: website

website:
  title: "Michaela Drouillard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

